version: '3.7'

services:
  someoneinmyhead:
    image: joseluisq/static-web-server:2-alpine
    container_name: 'someoneinmyhead'
    ports:
      - 80:80
    restart: unless-stopped
    environment:
      # Note: those envs are customizable but also optional
      - SERVER_ROOT=/var/public
      - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - ~/home/artem/data/someoneinmyhead:/var/public
      - ./config.toml:/etc/config.toml
    networks:
      - artynet
    labels:
      - io.containers.autoupdate=registry
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
networks:
  artynet:
    external: true
